openapi: 3.0.0
info:
  title: GYMbro2 API
  description: API documentation for GYMbro2 - Health and Fitness Platform
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Development server
tags:
  - name: Auth
    description: Authentication endpoints
  - name: Users
    description: User management endpoints
  - name: Posts
    description: Post management endpoints
  - name: Comments
    description: Comment management endpoints
  - name: Likes
    description: Like management endpoints
  - name: AI
    description: AI integration endpoints
  - name: Chat
    description: Chat functionality endpoints
paths:
  /api/auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      description: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  example: johndoe
                email:
                  type: string
                  format: email
                  example: john@example.com
                password:
                  type: string
                  format: password
                  example: StrongPassword123
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input
        '409':
          description: User already exists
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Authenticate user and get tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: john@example.com
                password:
                  type: string
                  format: password
                  example: StrongPassword123
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
  /api/chat/history/{userId}/{otherUserId}:
    get:
      tags:
        - Chat
      summary: Get chat history
      description: Retrieve chat history between two users
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: ID of the current user
        - name: otherUserId
          in: path
          required: true
          schema:
            type: string
          description: ID of the other user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Chat history retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /api/chat/contacts/{userId}:
    get:
      tags:
        - Chat
      summary: Get user contacts
      description: Retrieve list of all users except the current user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: ID of the current user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Contacts retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /api/chat/read/{userId}/{otherUserId}:
    put:
      tags:
        - Chat
      summary: Mark messages as read
      description: Mark all unread messages from a specific user as read
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: ID of the current user
        - name: otherUserId
          in: path
          required: true
          schema:
            type: string
          description: ID of the other user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Messages marked as read successfully
        '401':
          description: Unauthorized
        '500':
          description: Server error

components:
  schemas:
    Message:
      type: object
      properties:
        _id:
          type: string
          example: 5f8d0f3555b9d333d4b2f2e3
        sender:
          $ref: '#/components/schemas/User'
        receiver:
          $ref: '#/components/schemas/User'
        content:
          type: string
          example: היי, איך הולך?
        timestamp:
          type: string
          format: date-time
        read:
          type: boolean
          example: false
    User:
      type: object
      properties:
        _id:
          type: string
          example: 5f8d0f3555b9d333d4b2f2e3
        username:
          type: string
          example: johndoe
        email:
          type: string
          example: john@example.com
        profilePicture:
          type: string
          example: /uploads/profile/user123.jpg
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Post:
      type: object
      properties:
        _id:
          type: string
          example: 5f8d0f3555b9d333d4b2f2e3
        user:
          $ref: '#/components/schemas/User'
        content:
          type: string
          example: My workout today was amazing!
        image:
          type: string
          example: /uploads/posts/post123.jpg
        likesCount:
          type: integer
          example: 15
        commentsCount:
          type: integer
          example: 3
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 